# Supabase Auth Configuration

[auth]
# Site URL for redirects
site_url = "http://localhost:3000"

[auth.email]
# Enable email auth
enable_signup = true
enable_confirmations = true

# Email templates
[auth.email.template.confirmation]
subject = "Confirm your LifeNavigator account"
content_path = "./email-templates/confirmation.html"
redirect_to = "http://localhost:3000/auth/confirm"

# For production, update these URLs
# site_url = "https://lifenavigator.com"
# default = "https://lifenavigator.com/auth/confirm"